# Generated by Django 5.2.17 on 2026-09-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sandbox_instance_app', '0015_poolrolegrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxnetbirdaccess',
            name='role',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    "Declared role this access group is scoped to; '' for the sandbox's shared "
                    'access.'
                ),
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name='sandboxnetbirdaccess',
            name='access_group_id',
            field=models.CharField(
                default=None,
                help_text='Netbird group ID shared by all client peers of this role.',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='sandboxnetbirdaccess',
            name='access_setup_key_id',
            field=models.CharField(
                default=None,
                help_text="Netbird setup key ID for this role's access group.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='sandboxnetbirdaccess',
            name='access_setup_key_value',
            field=models.TextField(
                default=None,
                help_text="Plaintext setup key for this role's access group.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='sandboxnetbirdaccess',
            name='sandbox',
            field=models.ForeignKey(
                help_text='Sandbox these access resources belong to.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='netbird_access',
                to='sandbox_instance_app.sandbox',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='sandboxnetbirdaccess',
            unique_together={('sandbox', 'role')},
        ),
        migrations.CreateModel(
            name='SandboxRoleKeypair',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        help_text='Declared role this keypair is scoped to.', max_length=128
                    ),
                ),
                ('private_key', models.TextField(help_text='Private key for this role.')),
                ('public_key', models.TextField(help_text='Public key for this role.')),
                (
                    'sandbox',
                    models.ForeignKey(
                        help_text='Sandbox this role keypair belongs to.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='role_keypairs',
                        to='sandbox_instance_app.sandbox',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('sandbox', 'role')},
            },
        ),
    ]
