[project]
name = "crczp-terraform-client"
version = "1.0.4"
description = "Terraform Client"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
authors = [{ name = "cybersecurityhub.cz" }]
dependencies = [
    "crczp-python-commons",
    "crczp-openstack-lib",
    "crczp-aws-lib",
    "Jinja2>=3.1.6"
]

[project.urls]
GitHub = "https://github.com/cyberrangecz/backend-sandbox-platform"

[tool.uv.sources]
crczp-python-commons = { workspace = true }
crczp-openstack-lib = { workspace = true }
crczp-aws-lib = { workspace = true }

[build-system]
# TODO: Replace this with uv_build when it is it released for GA.
#   https://github.com/astral-sh/uv/issues/3957
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["crczp"]
exclude-packages = ["tests"]

[tool.ruff]
line-length = 100
preview = true

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.pylint]
# You can add pylint configs here or in .pylintrc

[tool.bandit]
skips = ["B101"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
